In [4]:
import torch
import torch.nn as nn
# 기본값 : torch.nn.Conv2d(in_channesls, out_channels, kernel_size, stride=1, padding=0, bias=True)
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=11, stride=4,padding=0)
conv

Conv2d(1, 1, kernel_size=(11, 11), stride=(4, 4))

In [6]:
inputs = torch.Tensor(1,1,227,227)
outputs = conv(inputs)
print(outputs)
outputs.shape

tensor([[[[-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629],
          [-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629],
          [-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629],
          ...,
          [-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629],
          [-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629],
          [-0.0629, -0.0629, -0.0629,  ..., -0.0629, -0.0629, -0.0629]]]],
       grad_fn=<ConvolutionBackward0>)


torch.Size([1, 1, 55, 55])

In [8]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=7,stride=2, padding=0)
print(conv)
inputs = torch.Tensor(1,1,64,64)
outputs = conv(inputs)
print(outputs)
print('outputs shape:',outputs.shape)

Conv2d(1, 1, kernel_size=(7, 7), stride=(2, 2))
tensor([[[[-3.8204e+15,  1.7347e+16, -3.1858e+17, -1.2590e+18, -1.4111e+18,
           -2.3775e+18, -2.5287e+17, -4.3708e+17, -3.1973e+17, -1.2589e+18,
                   nan,         nan,         nan,         nan,  1.3815e+16,
            1.5305e+17, -2.1889e+18, -2.7325e+16,  1.1163e+16,  8.1676e+15,
            1.7906e+18, -4.3861e+15,  1.7214e+17, -2.2069e+18,  2.1489e+07,
            2.9034e+06, -5.7707e+06,  7.6285e+05,  1.3649e+27],
          [ 3.0685e+07, -2.9959e+06, -1.8290e+17,  2.9497e+18, -3.6334e+17,
            2.9248e+17, -6.7773e+16, -6.7139e+16, -1.8290e+17,  2.9497e+18,
                   nan,         nan,         nan,         nan, -1.2336e+18,
           -1.3564e+18, -2.1096e+18, -4.3236e+15,  3.0222e+19,  1.2112e+19,
            1.2362e+19, -1.2423e+18, -1.3165e+18, -2.1095e+18, -1.4573e+16,
            1.7986e+18, -4.2638e+15,  1.7209e+17, -1.4266e+26],
          [ 1.4564e+09, -5.5366e+08,  2.7139e+18,  1.3981e+18, -

In [9]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=5,stride=1, padding=2)
print(conv)
inputs = torch.Tensor(1,1,32,632)
outputs = conv(inputs)
print(outputs)
print('outputs shape:',outputs.shape)

Conv2d(1, 1, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
tensor([[[[-5.8714e+36, -1.0167e+37,  1.3858e+37,  ...,  1.2019e+37,
           -3.4684e+36, -6.7631e-02],
          [ 4.8922e+36,  1.2401e+37,  9.8561e+36,  ...,  1.5708e+37,
           -9.4020e+36, -6.7631e-02],
          [ 6.7639e+36, -2.6724e+37, -1.9303e+37,  ...,  8.1002e+36,
            6.0172e+36, -1.0326e+07],
          ...,
          [ 6.7639e+36, -2.6724e+37, -1.9303e+37,  ..., -4.2655e+06,
            6.8778e+06, -1.0393e+07],
          [ 5.1581e+36, -2.1864e+37,  1.4235e+37,  ..., -2.2580e+07,
            5.3202e+06, -1.4757e+07],
          [-1.7318e+37,  2.9956e+37,  1.9962e+36,  ...,  8.9442e+06,
            1.4051e+07, -7.4151e+06]]]], grad_fn=<ConvolutionBackward0>)
outputs shape: torch.Size([1, 1, 32, 632])


In [10]:
# 예제 4
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=5,stride=1, padding=0)
print(conv)
inputs = torch.Tensor(1,1,32,64)
outputs = conv(inputs)
print(outputs)
print('outputs shape:',outputs.shape)

Conv2d(1, 1, kernel_size=(5, 5), stride=(1, 1))
tensor([[[[ 3.0487e+18, -1.5621e+18,  8.8145e+17,  ..., -1.5711e+07,
           -1.3783e+07, -1.2577e+07],
          [-1.0520e+18,  2.6245e+18, -1.0161e+18,  ...,  1.6682e+07,
           -8.4267e+06, -1.0031e+07],
          [-6.5414e+17, -4.0401e+18, -9.0341e+17,  ...,  1.7390e+06,
           -2.9280e+07, -4.9231e+06],
          ...,
          [-8.1771e+15,  2.6453e+07,  5.0214e+06,  ..., -5.4781e+06,
            7.7308e+06,  9.9828e+06],
          [-7.4067e+15,  9.6749e+06,  6.6999e+06,  ...,  7.5017e+21,
           -3.8268e+21,  2.2003e+21],
          [ 1.7577e+16,  5.4651e+06,  1.6996e+07,  ..., -2.5702e+21,
            6.5526e+21, -2.4590e+21]]]], grad_fn=<ConvolutionBackward0>)
outputs shape: torch.Size([1, 1, 28, 60])


In [11]:
# 예제 5
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3,stride=1, padding=1)
print(conv)
inputs = torch.Tensor(1,1,64,32)
outputs = conv(inputs)
print(outputs)
print('outputs shape:',outputs.shape)

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
tensor([[[[ 7.4871e+13, -1.3563e+14, -3.8833e+06,  ..., -1.6038e+06,
           -3.8833e+06, -2.4684e+07],
          [ 1.3108e+16, -2.3418e+16,  3.3320e+07,  ...,  1.3417e+07,
            3.3320e+07, -3.2219e+06],
          [ 6.6251e+15,  4.4324e+16,  2.8823e-01,  ...,  2.8823e-01,
            2.8823e-01,  2.8823e-01],
          ...,
          [ 2.9454e+07, -2.7923e+07,  2.8823e-01,  ..., -3.2239e+06,
            2.8823e-01,  2.8823e-01],
          [ 3.3341e+07, -3.2239e+06,  2.8823e-01,  ...,  2.8823e-01,
            2.8823e-01,  2.8823e-01],
          [ 2.8823e-01,  2.8823e-01,  2.8823e-01,  ...,  2.8823e-01,
            2.8823e-01,  2.8823e-01]]]], grad_fn=<ConvolutionBackward0>)
outputs shape: torch.Size([1, 1, 64, 32])


In [12]:
# torch.nn.MaxPool2d(kernel_size)

import torch
import torch.nn as nn
inputs = torch.Tensor(1,1,28,28)
conv1 = nn.Conv2d(in_channels=1, out_channels=5,kernel_size=5)
pool = nn.MaxPool2d(2)
out = conv1(inputs)
out2 = pool(out)
print(out.size())
print(out2.size())

torch.Size([1, 5, 24, 24])
torch.Size([1, 5, 12, 12])


# Lab-10-2 mnist cnn
1. 라이브러리를 가져온다 (torch, torchvision, matplotlib)
2. GPU 사용 설정하고 random value를 위한 seed 설정
3. 학습에 사용되는 parameter 설정 (learning_rate, training_epochs, batch_size, etc)
4. 데이터셋을 가져오고 (학습에 쓰기 편하기) loader 만들기
5. 학습 모델 만들기 (`class CNN(torch.nn.Module)`)
6. Loss function (Criterion)을 선택하고 최적화 도구 선택(Optimizer)
7. 모델 학습 및 Loss check(Criterion의 Output)
8. 학습된 모델의 성능을 확인한다.

## 우리가 만들 CNN 구조
- 데이터 -> Layer1(Conv->ReLU->MaxPool) -> Layer2(Conv->ReLU->MaxPool) -> view -> FC -> Cross Entropy Loss(SoftMax -> NLL loss)
- (Layer1) Convolution layer = (in_c=1, out_c=32, kernel_size=3, stride=1, padding=1)
- (Layer1) MaxPool layer = (kernel_size=2, stride=2)

- (Layer2) Convolution layer = (in_c=32, out_c=64, kernel_size=3, stride=1, padding=1)
- (Layer2) MaxPool layer = (kernel_size=2, stride=2)

- view => (batch_size x [7,7,64] => batch_size x [3136])
- Fully_Conneted layer => (input=3136, output=10)

In [2]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import torch.nn.init

In [3]:
device = 'cuda'

torch.manual_seed(777)
torch.cuda.manual_seed_all(777)

In [4]:
# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

In [6]:
# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

In [7]:
# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)

In [12]:
# CNN model
class CNN(torch.nn.Module):
    
    def __init__(self):
        super(CNN, self).__init__()
        # L1 ImgIn shape = (?, 28, 28, 1)
        # conv -> (?, 28, 28, 32)
        # Pool -> (?, 14, 14, 32)
        self.layer1 = torch.nn.Sequential(
            torch.nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2)
        )

        # L2 ImgIn shape = (?, 14, 14, 32)
        # Conv -> (?, 14, 14, 64)
        # Pool -> (?, 7, 7, 64)
        self.layer2 = torch.nn.Sequential(
            torch.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2)
        )
        # Final FC 7*7*64 inputs -> 10 outputs
        self.fc = torch.nn.Linear(in_features=7*7*64, out_features=10, bias=True)
        
        torch.nn.init.xavier_uniform_(self.fc.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1) 
        # Flatten them for FC
        out = self.fc(out)
        
        return out

In [13]:
# instantiate CNN model
model = CNN().to(device)

In [14]:
# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss().to(device)
# Softmax is internally computed
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [15]:
# train my model
total_batch = len(data_loader)
print('Learning started. It takes sometime.')
for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:
        # image is already size of (28x28), no reshape
        # label is not one-hot encoded
        X = X.to(device)
        Y = Y.to(device)

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('[Epoch: {:>4}] cost = {:>.9}'.format(epoch + 1, avg_cost))

print('Learning Finished!')

Learning started. It takes sometime.
[Epoch:    1] cost = 0.226737916
[Epoch:    2] cost = 0.0618809499
[Epoch:    3] cost = 0.0459988527
[Epoch:    4] cost = 0.0365079641
[Epoch:    5] cost = 0.0301498659
[Epoch:    6] cost = 0.0252439808
[Epoch:    7] cost = 0.0213218592
[Epoch:    8] cost = 0.018244192
[Epoch:    9] cost = 0.0148651777
[Epoch:   10] cost = 0.012360014
[Epoch:   11] cost = 0.0104663121
[Epoch:   12] cost = 0.00983833708
[Epoch:   13] cost = 0.00828739163
[Epoch:   14] cost = 0.00680823717
[Epoch:   15] cost = 0.00600036001
Learning Finished!


In [ ]:
# Test model and check accuracy
with torch.no_grad():
    X_test = mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)

    prediction = model(X_test)
    correct_prediction = torch.argmax(prediction, 1) == Y_test
    accuracy = correct_prediction.float().mean()
    print('Accuracy:', accuracy.item())